---

- name: Import vars tasks
  ansible.builtin.import_tasks: vars.yml
  tags:
    - system
    - cron
    - vars
    - cron-vars

- name: Import installation tasks
  ansible.builtin.import_tasks: install.yml
  tags:
    - system
    - cron
    - install
    - cron-install

- name: Import config tasks
  ansible.builtin.import_tasks: config.yml
  tags:
    - system
    - cron
    - config
    - cron-config

- name: Import service tasks
  ansible.builtin.import_tasks: service.yml
  tags:
    - system
    - cron
    - service
    - cron-service
