---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-qwe1/docker-debian:10-molecule}"
    privileged: true
    pre_build_image: true
    command: ""
    pull: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  # https://github.com/ansible/molecule/issues/1346
  log: true
scenario:
  name: default
